---
- hosts: mydc
  become: yes
  gather_facts: yes

  tasks:
    - name: Install the apache2 on the websrvgroup
      apt:
        name: apache2
        state: present
    - name: start the apache service
      service:
        name: apache2
        state: started

